version: '3.8'

services:
  # Backend Service (Flask/Gunicorn)
  backend:
    build: ./backend
    container_name: rag_backend
    env_file:
      - ./backend/.env # Pass environment variables from the .env file
    ports:
      - "5001:8000" # Map host port 5001 to container port 8000
    volumes:
      - ./backend/uploads:/app/uploads # Persist uploaded files
    depends_on:
      - qdrant

  # Frontend Service (React/Nginx)
  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "3000:80" # Map host port 3000 to container port 80
    depends_on:
      - backend

  # Qdrant Vector Database Service
  qdrant:
    image: qdrant/qdrant:v1.8.2
    container_name: rag_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persist the vector data

volumes:
  qdrant_storage: